-- No-op.
--
-- This migration previously attempted to create an index on User.workCountry
-- before the workCountry column existed. The index is now created in
-- 20260427210000_work_country_gate after the column is added.
