# -*- coding: utf-8 -*-
"""Content for the Coverboard feature guide. Every code path was checked
against the repository; every reference URL returned HTTP 200 when built."""

REPO = "https://github.com/GbengaOshinaga/Coverboard/blob/staging/"

# ── Verified references ────────────────────────────────────────────────
R = {
    "holiday": ("GOV.UK – Holiday entitlement", "https://www.gov.uk/holiday-entitlement-rights"),
    "holiday_entitlement": ("GOV.UK – Holiday entitlement: entitlement (5.6 weeks)", "https://www.gov.uk/holiday-entitlement-rights/entitlement"),
    "holiday_calc": ("GOV.UK – Calculate leave entitlement (part-time, part-year)", "https://www.gov.uk/holiday-entitlement-rights/calculate-leave-entitlement"),
    "holiday_pay": ("GOV.UK – Holiday pay: the basics", "https://www.gov.uk/holiday-entitlement-rights/holiday-pay-the-basics"),
    "holiday_tool": ("GOV.UK – Calculate your holiday entitlement (calculator)", "https://www.gov.uk/calculate-your-holiday-entitlement"),
    "irregular": ("GOV.UK – Calculating holiday pay for workers without fixed hours or pay", "https://www.gov.uk/government/publications/calculating-holiday-pay-for-workers-without-fixed-hours-or-pay"),
    "leaving": ("GOV.UK – Taking holiday before leaving a job", "https://www.gov.uk/holiday-entitlement-rights/taking-holiday-before-leaving-a-job"),
    "acas_holiday": ("Acas – Checking holiday entitlement", "https://www.acas.org.uk/checking-holiday-entitlement"),
    "acas_holiday_sick": ("Acas – Holiday and sickness", "https://www.acas.org.uk/holiday-sickness-leave"),
    "wtr": ("legislation.gov.uk – Working Time Regulations 1998", "https://www.legislation.gov.uk/uksi/1998/1833/contents"),
    "wtr13": ("legislation.gov.uk – WTR reg. 13 (annual leave)", "https://www.legislation.gov.uk/uksi/1998/1833/regulation/13"),
    "wtr16": ("legislation.gov.uk – WTR reg. 16 (holiday pay)", "https://www.legislation.gov.uk/uksi/1998/1833/regulation/16"),
    "wtr10": ("legislation.gov.uk – WTR reg. 10 (daily rest)", "https://www.legislation.gov.uk/uksi/1998/1833/regulation/10"),
    "rest": ("GOV.UK – Rest breaks at work", "https://www.gov.uk/rest-breaks-work"),
    "maxhours": ("GOV.UK – Maximum weekly working hours", "https://www.gov.uk/maximum-weekly-working-hours"),
    "bank": ("GOV.UK – UK bank holidays", "https://www.gov.uk/bank-holidays"),
    "ssp": ("GOV.UK – Statutory Sick Pay (SSP)", "https://www.gov.uk/statutory-sick-pay"),
    "ssp_amount": ("GOV.UK – SSP: what you'll get (£123.25 or 80%, days normally worked)", "https://www.gov.uk/statutory-sick-pay/what-youll-get"),
    "ssp_employer": ("GOV.UK – Employers: Statutory Sick Pay", "https://www.gov.uk/employers-sick-pay"),
    "ssp_pay": ("GOV.UK – Employers: SSP, what you need to pay", "https://www.gov.uk/employers-sick-pay/what-you-need-to-pay"),
    "ssp_elig": ("GOV.UK – Employers: SSP eligibility and form SSP1", "https://www.gov.uk/employers-sick-pay/eligibility-and-form-ssp1"),
    "sick_leave": ("GOV.UK – Taking sick leave (self-certification, fit notes)", "https://www.gov.uk/taking-sick-leave"),
    "fitnote": ("GOV.UK – Fit note guidance (collection)", "https://www.gov.uk/government/collections/fit-note"),
    "era2025": ("legislation.gov.uk – Employment Rights Act 2025", "https://www.legislation.gov.uk/ukpga/2025/36/contents"),
    "era_facts": ("GOV.UK – Employment Rights Bill factsheets", "https://www.gov.uk/government/publications/employment-rights-bill-factsheets"),
    "rates": ("GOV.UK – Rates and thresholds for employers 2026 to 2027", "https://www.gov.uk/guidance/rates-and-thresholds-for-employers-2026-to-2027"),
    "maternity": ("GOV.UK – Maternity pay and leave", "https://www.gov.uk/maternity-pay-leave"),
    "maternity_leave": ("GOV.UK – Maternity leave (52 weeks)", "https://www.gov.uk/maternity-pay-leave/leave"),
    "maternity_employer": ("GOV.UK – Employers: maternity pay and leave", "https://www.gov.uk/employers-maternity-pay-leave"),
    "maternity_employer_leave": ("GOV.UK – Employers: maternity leave (incl. KIT days)", "https://www.gov.uk/employers-maternity-pay-leave/leave"),
    "paternity": ("GOV.UK – Paternity pay and leave", "https://www.gov.uk/paternity-pay-leave"),
    "paternity_employer": ("GOV.UK – Employers: paternity pay and leave", "https://www.gov.uk/employers-paternity-pay-leave"),
    "spl": ("GOV.UK – Shared Parental Leave and Pay", "https://www.gov.uk/shared-parental-leave-and-pay"),
    "spl_employer": ("GOV.UK – Shared Parental Leave: employer guidance (SPLIT days)", "https://www.gov.uk/shared-parental-leave-and-pay/employer-guidance"),
    "adoption": ("GOV.UK – Adoption pay and leave", "https://www.gov.uk/adoption-pay-leave"),
    "neonatal": ("GOV.UK – Neonatal care pay and leave", "https://www.gov.uk/neonatal-care-pay-leave"),
    "neonatal_employer": ("GOV.UK – Employers: neonatal care pay and leave", "https://www.gov.uk/employers-neonatal-care-pay-leave"),
    "bereavement": ("GOV.UK – Parental Bereavement Pay and Leave", "https://www.gov.uk/parental-bereavement-pay-leave"),
    "upl": ("GOV.UK – Unpaid parental leave", "https://www.gov.uk/parental-leave"),
    "carers": ("GOV.UK – Carer's leave", "https://www.gov.uk/carers-leave"),
    "rtw": ("GOV.UK – Check a job applicant's right to work", "https://www.gov.uk/check-job-applicant-right-to-work"),
    "acas_absence": ("Acas – Absence from work", "https://www.acas.org.uk/absence-from-work"),
    "ico_sar": ("ICO – Right of access (subject access requests)", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/individual-rights/individual-rights/right-of-access/"),
    "ico_storage": ("ICO – Storage limitation principle", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/data-protection-principles/a-guide-to-the-data-protection-principles/storage-limitation/"),
    "ico_employment": ("ICO – Employment practices and data protection", "https://ico.org.uk/for-organisations/uk-gdpr-guidance-and-resources/employment/"),
    "ico_cookies": ("ICO – Cookies and similar technologies (PECR)", "https://ico.org.uk/for-organisations/direct-marketing-and-privacy-and-electronic-communications/guide-to-pecr/cookies-and-similar-technologies/"),
}

# Product/engineering docs (not legal sources) — used for integrations.
D = {
    "nextjs": ("Next.js documentation", "https://nextjs.org/docs"),
    "prisma": ("Prisma documentation", "https://www.prisma.io/docs"),
    "nextauth": ("NextAuth.js documentation", "https://next-auth.js.org/"),
    "stripe_billing": ("Stripe – Billing and subscriptions", "https://docs.stripe.com/billing"),
    "stripe_tax": ("Stripe – Tax", "https://docs.stripe.com/tax"),
    "stripe_webhooks": ("Stripe – Webhooks", "https://docs.stripe.com/webhooks"),
    "vercel_regions": ("Vercel – Function regions", "https://vercel.com/docs/functions/configuring-functions/region"),
    "vercel_cron": ("Vercel – Cron jobs", "https://vercel.com/docs/cron-jobs"),
    "resend": ("Resend documentation", "https://resend.com/docs"),
    "upstash": ("Upstash – Rate limiting", "https://upstash.com/docs/redis/sdks/ratelimit-ts/overview"),
    "sentry": ("Sentry – Next.js", "https://docs.sentry.io/platforms/javascript/guides/nextjs/"),
    "posthog": ("PostHog documentation", "https://posthog.com/docs"),
    "slack_api": ("Slack API – Slash commands and interactivity", "https://api.slack.com/interactivity"),
    "jira_api": ("Atlassian – Jira Cloud REST API", "https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/"),
    "csp": ("MDN – Content Security Policy", "https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP"),
    "rfc8058": ("RFC 8058 – One-click unsubscribe", "https://www.rfc-editor.org/rfc/rfc8058"),
}

CHAPTERS = [
    # (id, title, colour, intro)
    ("start", "Getting started & people", "#2563EB",
     "How a team arrives in Coverboard: signing up, choosing a plan, onboarding, inviting people and managing who they are and what they can do."),
    ("leave", "Leave & holiday", "#0D9488",
     "Booking time off, how entitlement is worked out under UK law, and the rules that turn a date range into days, weeks or hours off."),
    ("family", "Family & statutory leave", "#9333EA",
     "Maternity, paternity, adoption, shared parental, neonatal, bereavement, unpaid parental and carer's leave — and the pay that goes with them."),
    ("sickness", "Sickness, SSP & fit notes", "#E11D48",
     "Reporting and logging sickness, Statutory Sick Pay, fit notes and absence monitoring."),
    ("cover", "Cover & shifts", "#059669",
     "The heart of the product: minimum staffing per location and shift, who could cover a gap, and asking staff to cover."),
    ("pay", "Pay, payroll & reports", "#D97706",
     "Earnings history, holiday pay, the payroll export and the reports managers use to stay compliant."),
    ("data", "Compliance, privacy & security", "#0891B2",
     "Right to work, audit logs, data protection (UK GDPR) and the security controls protecting the app."),
    ("integrations", "Billing & integrations", "#EA580C",
     "Plans and payments with Stripe, plus Slack, Jira, email and analytics."),
    ("growth", "Website & growth", "#DB2777",
     "The public website, SEO guides and free tools, and the alerts that tell you when someone signs up."),
]

# ── Features ───────────────────────────────────────────────────────────
# id, chapter, title, plan, summary, how[], code[(path, note)], refs[keys], watch, related[]
FEATURES = [
    # ── Getting started ──
    dict(id="signup", ch="start", title="Sign-up, plans & trials", plan="All plans",
         summary="A new team signs up with email and password or Google, picks a plan, and gets an organisation with themselves as admin. Paid plans start a 14-day trial; Free has no trial.",
         how=["Plain /signup and every “Start free” button default to the Free plan; pricing cards pass ?plan= for paid tiers.",
              "Google sign-up carries the chosen plan through to /welcome, where the team is created.",
              "provisionTeam() creates the organisation, the admin user and (for paid plans) the Stripe customer and trialing subscription. Stripe failures never block sign-up.",
              "Every sign-up path runs through provisionTeam(), which also emails you a signup alert."],
         code=[("src/app/(auth)/signup/page.tsx", "Sign-up form and plan picker"),
               ("src/app/welcome/page.tsx", "Google sign-up completion"),
               ("src/app/api/auth/signup/route.ts", "Email/password sign-up API"),
               ("src/app/api/auth/complete-signup/route.ts", "Google sign-up API"),
               ("src/lib/provision-team.ts", "provisionTeam(): org, admin, Stripe"),
               ("src/lib/trial.ts", "Trial countdown")],
         refs=[], docs=["stripe_billing"], related=["billing", "signupalerts", "onboarding"]),
    dict(id="onboarding", ch="start", title="Onboarding", plan="All plans",
         summary="A three-step setup: which countries the team works in, the industry, and inviting the first people. Choosing the UK switches on UK statutory leave types and bank holidays.",
         how=["Runs once per team — the API refuses a second run so an old tab can't reset settings.",
              "Selecting GB calls enableUkStatutoryLeaveTypes() (statutory leave types + policies + bank holidays).",
              "Invite rows default to the first chosen country; invites without one used to be silently dropped (fixed).",
              "Healthcare teams are offered “cover by location” straight away."],
         code=[("src/app/(onboarding)/onboarding/page.tsx", "Onboarding wizard"),
               ("src/app/api/onboarding/complete/route.ts", "Saves the setup, creates invites"),
               ("src/lib/uk-statutory.ts", "enableUkStatutoryLeaveTypes()"),
               ("src/lib/country-policies.ts", "Leave rules per country")],
         refs=["holiday", "bank"], related=["invites", "statutorytypes"]),
    dict(id="invites", ch="start", title="Inviting people (set-password links)", plan="All plans",
         summary="People are added from onboarding, the Team page, or a CSV bulk import. They receive an email with a one-time “Set your password” link — never a password.",
         how=["Accounts start with a random password nobody knows (unusablePasswordHash()).",
              "The link reuses password-reset tokens: single use, valid 7 days, replaced by any newer link.",
              "Using the link also verifies their email address.",
              "Resend invite only sends a fresh link; it never touches an existing password."],
         code=[("src/lib/invite-links.ts", "createSetPasswordLink(), unusablePasswordHash()"),
               ("src/lib/email-notifications.ts", "sendTeamInviteEmail()"),
               ("src/app/api/team-members/route.ts", "Add a member"),
               ("src/app/api/team-members/bulk-import/route.ts", "CSV bulk import"),
               ("src/app/api/team-members/[id]/resend-invite/route.ts", "Resend invite"),
               ("src/app/(auth)/reset-password/page.tsx", "“Welcome to Coverboard / Choose your password” page")],
         refs=["ico_employment"], related=["team"]),
    dict(id="team", ch="start", title="Team members & profiles", plan="All plans",
         summary="The Team page lists everyone with their location, contract and work country. Each profile holds contract details, start date, right-to-work status, earnings history and working pattern.",
         how=["Work country (not “location”) decides which statutory rules apply.",
              "New members default to the team's most common work country (it used to be Nigeria).",
              "The start date is saved on add and edit (edit used to drop it) — it drives starter proration and SMP service checks.",
              "Days worked per week is kept in step with the working pattern automatically."],
         code=[("src/app/(dashboard)/team/page.tsx", "Team list, add/edit dialogs"),
               ("src/app/(dashboard)/team/[id]/page.tsx", "Member profile"),
               ("src/components/team/member-form.tsx", "Add/edit form"),
               ("src/components/team/member-card.tsx", "Member card"),
               ("src/app/api/team-members/[id]/route.ts", "Update a member")],
         refs=["holiday_calc"], related=["workingweek", "rtw", "earnings"]),
    dict(id="roles", ch="start", title="Roles & permissions", plan="Admin limits vary by plan",
         summary="Three roles: Admin (everything, including billing and settings), Manager (approve leave, log sickness, manage cover) and Member (their own time off, cover requests).",
         how=["Members can't open Reports or Audit (middleware redirects them).",
              "You can't approve your own leave when another approver exists; a sole approver's request auto-approves and is labelled so.",
              "Cover suggestions and who-was-asked lists are only shown to managers and admins.",
              "Sickness notes are only visible to the person and admins."],
         code=[("src/middleware.ts", "Route protection"),
               ("src/lib/member-route-access.ts", "Pages members can't open"),
               ("src/lib/leave-requests/review.ts", "Segregation of duties on approval"),
               ("src/lib/plans.ts", "Admin seats per plan")],
         refs=["ico_employment"], docs=["nextauth"], related=["audit"]),

    # ── Leave & holiday ──
    dict(id="requests", ch="leave", title="Leave requests & approvals", plan="All plans",
         summary="Staff request time off; managers approve or reject. Requests check notice periods, balances, overlap with colleagues and minimum cover before they're submitted.",
         how=["Notice is counted in whole calendar days; sickness never needs notice.",
              "Pending requests can be withdrawn; approved leave only before it starts.",
              "Approving below minimum cover asks for an explicit override, recorded in the audit log.",
              "Approvals also update Bradford scores and notify by email and Slack."],
         code=[("src/lib/leave-requests/create.ts", "createLeaveRequest(): every rule on booking"),
               ("src/lib/leave-requests/review.ts", "reviewLeaveRequest(): approve/reject"),
               ("src/lib/leave-requests/rules.ts", "Pure rules (notice, on-behalf, end-date changes)"),
               ("src/components/leave/request-form.tsx", "Request form"),
               ("src/components/leave/request-card.tsx", "Request card (approve, cover, fit notes)"),
               ("src/app/(dashboard)/requests/page.tsx", "Requests page")],
         refs=["holiday", "acas_holiday", "acas_holiday_sick"], related=["balances", "covercheck", "audit"]),
    dict(id="balances", ch="leave", title="Leave balances & entitlement", plan="Pro-rata: Starter+",
         summary="Each person's allowance, days used, pending and remaining, per leave type and calendar year. UK entitlement is 5.6 weeks of their working week, capped at 28 days.",
         how=["Entitlement = 5.6 × working days per week, rounded up, capped at 28 — 28 for a 5-day week, 17 for 3 days.",
              "Mid-year starters get their share of the year from their start date, rounded up (never down).",
              "Days taken only count days they'd actually have worked.",
              "Bank holidays are either included in the 28 or added on top (a team setting).",
              "Week-based statutory leave converts weeks to days using their working week."],
         code=[("src/lib/leave-balances.ts", "getUserLeaveBalances()"),
               ("src/lib/uk-compliance.ts", "calculateUkProRatedAnnualLeave()"),
               ("src/lib/working-week.ts", "prorateForStartDate(), countWorkingDays()"),
               ("src/components/dashboard/leave-balances.tsx", "Balance cards")],
         refs=["holiday_entitlement", "holiday_calc", "wtr13", "holiday_tool", "wtr"],
         watch="Proration and part-time maths were fixed on 4 Oct 2026 after tester feedback — see Known limitations.",
         related=["workingweek", "irregular", "bankhol"]),
    dict(id="workingweek", ch="leave", title="The working week (one source of truth)", plan="All plans",
         summary="Which days each person works. Holiday pay, entitlement, days taken, SSP and week-based family leave all depend on it.",
         how=["If they have a working pattern, their working days are the weekdays it schedules.",
              "Otherwise the stored days-per-week is used, with Monday–Friday assumed for counting.",
              "Saving a pattern updates daysWorkedPerWeek and qualifyingDaysPerWeek to match.",
              "Added 4 Oct 2026 — before this, many calculations assumed 5 days."],
         code=[("src/lib/working-week.ts", "Pure helpers (+ tests)"),
               ("src/lib/working-week-server.ts", "getWorkingWeek(), syncDaysFromPattern()"),
               ("src/app/api/team-members/[id]/work-pattern/route.ts", "Pattern save syncs day counts")],
         refs=["holiday_calc", "ssp_amount"], related=["balances", "holidaypay", "ssp", "patterns"]),
    dict(id="irregular", ch="leave", title="Irregular-hours & zero-hours holiday", plan="Pro-rata: Starter+",
         summary="Workers without fixed hours accrue holiday at 12.07% of the hours they work, measured in hours (the post-April 2024 method).",
         how=["Admins log weekly hours in Reports → Weekly hours; accrual = 12.07% of hours logged this year.",
              "Bookings deduct hours (default: days × their average day, editable).",
              "Accepted cover hours are shown beside each week — not added automatically, to avoid double counting.",
              "Carry-over for these staff is in hours."],
         code=[("src/lib/uk-compliance.ts", "calculateIrregularHoursAccrual()"),
               ("src/lib/leave-balances.ts", "Hours-unit balances"),
               ("src/app/api/weekly-hours/route.ts", "Weekly hours API"),
               ("src/app/tools/irregular-hours-holiday-calculator/calculator.tsx", "Public calculator")],
         refs=["irregular", "holiday_calc"], related=["carryover", "coverpay"]),
    dict(id="bankhol", ch="leave", title="Bank holidays", plan="Region config: Starter+",
         summary="Bank holidays for England & Wales, Scotland and Northern Ireland are seeded and shown on the calendar; teams choose whether they count within the 28 days.",
         how=["The team picks its bank-holiday region in Settings.",
              "Starters only lose the bank holidays after they join.",
              "Each cover location decides whether minimum cover applies on bank holidays."],
         code=[("src/lib/uk-compliance.ts", "Easter & bank holiday calculation"),
               ("src/app/api/holidays/route.ts", "Holidays API"),
               ("src/lib/coverDays.ts", "Whether cover applies on a day")],
         refs=["bank", "holiday_entitlement"], related=["balances"]),
    dict(id="carryover", ch="leave", title="Carry-over & year-end rollover", plan="Carry-over rules: Starter+",
         summary="At year end, unused annual leave (capped by the team's carry-over maximum) moves into next year, with an optional expiry date.",
         how=["Preview first, then run; the run is audited.",
              "Hours-based staff carry hours (cap converted at their average day), rounded to 2 decimals.",
              "Expired carry-over stops counting towards the allowance."],
         code=[("src/app/api/carry-over/process/route.ts", "Rollover preview/run"),
               ("src/lib/leave-balances.ts", "Carry-over in balances")],
         refs=["holiday", "leaving"], related=["balances"]),
    dict(id="calendar", ch="leave", title="Team calendar", plan="All plans",
         summary="A month view of approved absences, bank holidays, accepted cover shifts and (per location) whether minimum cover is met each day.",
         how=["Managers see everyone; members see their own leave and cover.",
              "Filter by location; green outlined chips are cover shifts."],
         code=[("src/app/(dashboard)/calendar/page.tsx", "Calendar page"),
               ("src/components/calendar/month-view.tsx", "Month grid"),
               ("src/components/calendar/day-cell.tsx", "Day cell"),
               ("src/app/api/cover-shifts/route.ts", "Cover shifts for the calendar")],
         refs=["bank"], related=["coverpay"]),

    # ── Family leave ──
    dict(id="statutorytypes", ch="family", title="Statutory leave types (in weeks)", plan="Parental tracker: Growth+",
         summary="UK statutory family leave is set in weeks of the person's normal working week, then converted to days for them.",
         how=["Paternity 2 weeks · Bereavement 2 · Unpaid parental 4/year (18 per child) · Carer's 1 · Maternity 52 · Adoption 52 · Shared parental 50 · Neonatal 12.",
              "LeaveType.allowanceUnit = WEEKS; balances multiply by their working days (2 weeks = 10 days on 5 days, 6 on 3).",
              "A migration converted existing teams still on the old day counts (custom values untouched)."],
         code=[("src/lib/country-policies.ts", "UK rules (allowanceUnit: WEEKS)"),
               ("src/lib/uk-statutory.ts", "Creates the types per team"),
               ("prisma/schema.prisma", "LeaveType.allowanceUnit"),
               ("src/lib/leave-balances.ts", "Weeks → days per person")],
         refs=["paternity", "bereavement", "upl", "carers", "maternity_leave"], related=["maternity", "workingweek"]),
    dict(id="maternity", ch="family", title="Maternity leave & SMP", plan="Growth+",
         summary="52 weeks' maternity leave (a day-one right). Statutory Maternity Pay: 6 weeks at 90% of average weekly earnings, then 33 weeks at the lower of the flat rate or 90%.",
         how=["Phase dates and weekly rates are stamped on the request.",
              "SMP needs average earnings ≥ the Lower Earnings Limit and 26 weeks' service by the qualifying week (uses the expected due date).",
              "Average weekly earnings come from the 8 weeks before the relevant date."],
         code=[("src/lib/smpCalculator.ts", "SMP phases, rates, AWE"),
               ("src/lib/leave-requests/create.ts", "Stamps SMP on booking")],
         refs=["maternity", "maternity_employer", "rates"], related=["kit", "earnings"]),
    dict(id="paternity", ch="family", title="Paternity, adoption & shared parental", plan="Growth+",
         summary="Paternity leave (1 or 2 weeks, may be split, within 52 weeks of birth), adoption leave (mirrors maternity) and shared parental leave (up to 50 weeks shared).",
         how=["Paternity must start within 52 weeks of the birth/placement date.",
              "SPL requires curtailment of maternity/adoption leave to be confirmed."],
         code=[("src/lib/leave-requests/create.ts", "Paternity window, SPL checks"),
               ("src/lib/country-policies.ts", "Rules and allowances")],
         refs=["paternity", "paternity_employer", "adoption", "spl", "spl_employer"], related=["kit"]),
    dict(id="neonatal", ch="family", title="Neonatal care leave & pay", plan="Growth+",
         summary="Up to 12 weeks (one per 7 full days in neonatal care), pay at the lower of the flat rate or 90% of earnings. In force from 6 April 2025.",
         how=["Pay requires earnings ≥ LEL and 26 weeks' continuous service."],
         code=[("src/lib/neonatalPay.ts", "Neonatal pay")],
         refs=["neonatal", "neonatal_employer"], related=["maternity"]),
    dict(id="kit", ch="family", title="KIT & SPLIT days", plan="Growth+",
         summary="“Keeping in touch” days during maternity/adoption leave and SPLIT days during shared parental leave can be recorded on the request.",
         how=["Managers record days used on the request (validated 0–20)."],
         code=[("src/app/api/leave-requests/[id]/route.ts", "kitDaysUsed / splitDaysUsed")],
         refs=["maternity_employer_leave", "spl_employer"], related=["maternity"]),
    dict(id="otherfamily", ch="family", title="Bereavement, unpaid parental & carer's leave", plan="All plans",
         summary="Parental bereavement leave (2 weeks), unpaid parental leave (18 weeks per child, max 4 a year) and carer's leave (1 week a year).",
         how=["The unpaid parental cap is 4 × their working days a year, counted on days they work.",
              "The app doesn't track individual children, so the cap is per person per year."],
         code=[("src/lib/leave-requests/create.ts", "Unpaid parental cap"),
               ("src/lib/country-policies.ts", "Allowances")],
         refs=["bereavement", "upl", "carers"], related=["statutorytypes"]),

    # ── Sickness ──
    dict(id="logsick", ch="sickness", title="Logging sickness (manager)", plan="All plans",
         summary="The 7:10am phone call: a manager records sickness for someone in a few taps and immediately sees which shifts are short and who could cover.",
         how=["Only sickness types; recorded as approved straight away; no evidence needed.",
              "The confirmation shows the cover impact, grouped by person for long absences.",
              "The audit log records the manager as the actor and who it was for."],
         code=[("src/app/(dashboard)/requests/log-sickness/page.tsx", "Log sickness page"),
               ("src/components/leave/log-sickness-form.tsx", "Form + cover result"),
               ("src/lib/leave-requests/create.ts", "onBehalfOfUserId path")],
         refs=["sick_leave", "acas_absence"], related=["ssp", "covercheck", "enddate"]),
    dict(id="enddate", ch="sickness", title="Changing a sickness end date", plan="All plans",
         summary="Off longer, or back early? Managers move the end date so it stays one absence (one Bradford spell, one SSP period).",
         how=["SSP, Bradford, hours and fit-note status are recalculated; later linked SSP absences too.",
              "Can't overlap another sickness record for the same person.",
              "Shows the new cover impact after saving."],
         code=[("src/lib/leave-requests/change-end-date.ts", "changeSicknessEndDate()"),
               ("src/components/leave/request-card.tsx", "Change end date control")],
         refs=["ssp_employer"], related=["ssp", "bradford", "fitnotes"]),
    dict(id="ssp", ch="sickness", title="Statutory Sick Pay (SSP)", plan="Growth+",
         summary="From 6 April 2026: SSP is the lower of £123.25 a week or 80% of average weekly earnings, paid from the first day, for days the person normally works, for up to 28 weeks.",
         how=["Average weekly earnings: earnings in the 8 weeks before the absence ÷ weeks recorded.",
              "Payable days: their qualifying (working) days only — 6 days for a 3-day worker off two weeks.",
              "Absences within 56 days link into one period; the 28-week cap covers the whole linked chain.",
              "Before 6 April 2026 the old rules apply: Lower Earnings Limit and 3 waiting days.",
              "Reports show SSP days, daily rate, cost to date and cost of the whole absence."],
         code=[("src/lib/uk-compliance.ts", "calculateSspEntitlement(), payable days"),
               ("src/lib/leave-requests/ssp-spell.ts", "computeSspForSpell(), linked chain"),
               ("src/lib/sickness-spells.ts", "linkedPriorChain()"),
               ("src/lib/smpCalculator.ts", "getAweForUser() (shared AWE)"),
               ("src/app/api/reports/uk-compliance/route.ts", "SSP liability report"),
               ("src/app/tools/ssp-calculator/calculator.tsx", "Public SSP calculator")],
         refs=["ssp_amount", "ssp_employer", "ssp_pay", "ssp_elig", "era2025", "rates", "ssp", "era_facts"],
         watch="SSP days already stored on production before 4 Oct 2026 used the old weekday rule and aren't recalculated automatically.",
         related=["workingweek", "earnings", "enddate"]),
    dict(id="fitnotes", ch="sickness", title="Fit notes", plan="Recording: all · alerts: Growth+",
         summary="The first 7 days of sickness are self-certified. From day 8 a fit note is needed; managers record its dates (no document or diagnosis is stored).",
         how=["Status per absence: self-certified / needed from (day 8) / covered.",
              "Several notes can chain (renewals); gaps are spotted.",
              "Recorded notes set the evidence flag the overdue list and Monday email read; typed notes don't count.",
              "Overdue: absences past day 7 without cover, still going or ended within 90 days."],
         code=[("src/lib/fit-notes.ts", "fitNoteStatus() (+ tests)"),
               ("src/lib/leave-requests/fit-notes.ts", "Record/remove, sync evidence"),
               ("src/components/leave/fit-note-section.tsx", "Fit note panel on requests"),
               ("src/lib/fit-note-alerts.ts", "Overdue selection"),
               ("src/components/dashboard/fit-notes-due.tsx", "Fit notes due card"),
               ("src/app/api/cron/fit-note-alerts/route.ts", "Monday alert email")],
         refs=["fitnote", "sick_leave"], related=["ssp"]),
    dict(id="bradford", ch="sickness", title="Bradford Factor", plan="Growth+",
         summary="An absence score: spells² × days. Many short absences score higher than one long one. Used to prompt a conversation, not as an automatic trigger.",
         how=["Overlapping records count as one spell; days aren't double-counted.",
              "One shared calculation for stored scores and the report."],
         code=[("src/lib/sickness-spells.ts", "bradfordForSickness()"),
               ("src/lib/leave-requests/bradford.ts", "recomputeBradfordScore()"),
               ("src/app/api/reports/uk-compliance/route.ts", "Bradford report")],
         refs=["acas_absence"],
         watch="The Bradford Factor is an HR convention, not a legal requirement; use it fairly and consider disability and pregnancy-related absence.",
         related=["trends"]),
    dict(id="trends", ch="sickness", title="Absence trends", plan="Scale+",
         summary="Monthly working days of sickness per person over 12 months, to spot rising patterns early.",
         how=["Separate from Bradford (a single rolling number)."],
         code=[("src/lib/absence-trends.ts", "Trend calculation"),
               ("src/components/reports/absence-trends-section.tsx", "Report section")],
         refs=["acas_absence"], related=["bradford"]),

    # ── Cover ──
    dict(id="locations", ch="cover", title="Locations & minimum cover", plan="All plans",
         summary="Group people by location (a care home, a kitchen) and set the minimum number on duty — per day, or per shift once shifts are set up.",
         how=["Switched on in Settings → Optional features; managed in Settings → Locations.",
              "Each location decides whether weekends and bank holidays need cover.",
              "In code and the database these are still called “regions”."],
         code=[("src/app/(dashboard)/settings/regions/page.tsx", "Locations settings"),
               ("src/app/api/regions/route.ts", "Locations API"),
               ("src/lib/regionCover.ts", "Daily cover and cover checks"),
               ("src/lib/coverDays.ts", "Which days cover applies")],
         refs=["rest"], related=["patterns", "covercheck"]),
    dict(id="patterns", ch="cover", title="Shift types & working patterns", plan="All plans",
         summary="Shift types (Day 08:00–20:00, Night 20:00–08:00) with a minimum per weekday, and each person's weekly pattern of shifts.",
         how=["A shift belongs to the day it starts (Thursday's night runs into Friday).",
              "Pattern changes take effect today; history stays accurate.",
              "People without a pattern don't count towards shifts — the dashboard warns."],
         code=[("src/components/settings/region-shifts-dialog.tsx", "Shift types editor"),
               ("src/components/team/work-pattern-card.tsx", "Pattern editor"),
               ("src/app/api/team-members/[id]/work-pattern/route.ts", "Save a pattern"),
               ("src/lib/workPattern.ts", "Ending old patterns")],
         refs=["rest"], related=["engine", "workingweek"]),
    dict(id="engine", ch="cover", title="The cover engine", plan="All plans",
         summary="The single source of truth for “is this shift covered?” — available = scheduled − on leave + accepted cover — and, for short shifts, who could cover and who can't.",
         how=["Candidates: not on the shift, not on leave, and 11 hours' rest either side (Working Time Regulations).",
              "Ruled out shows why: on leave, needs rest, or already covering a nearby shift.",
              "Shows contract type and hours already scheduled that week.",
              "Pure function, no database, heavily tested."],
         code=[("src/lib/shiftCover.ts", "computeShiftCover() (+ tests)"),
               ("src/lib/regionCover.ts", "Loads data, checkRegionalCover()"),
               ("src/lib/cover-grouping.ts", "Group short shifts by person")],
         refs=["wtr10", "rest", "maxhours", "wtr"], related=["covercheck", "offers"]),
    dict(id="covercheck", ch="cover", title="Cover warnings & suggestions", plan="All plans",
         summary="Wherever leave affects staffing — booking, approving, logging sickness, changing dates — Coverboard shows which shifts would be short and who could cover.",
         how=["One short shift: a simple list. Several: grouped by person with “Ask for all”.",
              "The request card's cover badge only says OK when shifts really are covered.",
              "Dashboard “Cover today” widget per location."],
         code=[("src/components/leave/regional-cover-warning.tsx", "Warning block"),
               ("src/components/leave/cover-options.tsx", "One shift: candidates + Ask"),
               ("src/components/leave/cover-by-person.tsx", "Grouped view"),
               ("src/components/leave/regional-cover-panel.tsx", "Panel on request cards"),
               ("src/components/dashboard/region-cover-widget.tsx", "Dashboard widget"),
               ("src/app/api/cover-check/route.ts", "Cover check API")],
         refs=["rest"], related=["engine", "offers"]),
    dict(id="offers", ch="cover", title="Cover requests (ask, accept, decline)", plan="All plans",
         summary="Managers ask people to cover a short shift; they accept or decline in the app. Accepting puts them on the shift and closes the gap.",
         how=["Re-checked when asked and when accepted (still short, not on leave, rested).",
              "First to accept takes it (a database lock stops two people filling one gap); other asks close as filled.",
              "Either side can pull out later (manager withdraws / person drops out), with emails both ways.",
              "Managers see a “Cover updates” card; staff see a count in the sidebar."],
         code=[("src/lib/cover-offers.ts", "Create, respond, withdraw, drop out"),
               ("src/app/api/cover-offers/route.ts", "Ask / list (+ batch)"),
               ("src/app/(dashboard)/cover-requests/page.tsx", "Staff page"),
               ("src/components/cover/cover-requests-list.tsx", "Accept / decline / drop out"),
               ("src/components/dashboard/cover-updates-list.tsx", "Manager updates card"),
               ("prisma/schema.prisma", "CoverOffer model")],
         refs=["wtr10", "rest"], related=["coverpay", "engine"]),
    dict(id="coverpay", ch="cover", title="Cover in payroll, calendar & hours", plan="All plans",
         summary="Accepted cover is extra paid work: it appears in the payroll export, on the calendar and beside weekly hours.",
         how=["One loader for all three so they agree.",
              "Cover hours are shown beside logged weekly hours, never added automatically."],
         code=[("src/lib/cover-shifts.ts", "loadAcceptedCoverShifts(), shiftLengthHours()"),
               ("src/app/api/reports/cover-shifts/route.ts", "Cover shifts export"),
               ("src/components/reports/cover-shifts-section.tsx", "Payroll section")],
         refs=["irregular", "holiday_pay"], related=["payroll", "irregular", "calendar"]),

    # ── Pay & reports ──
    dict(id="earnings", ch="pay", title="Earnings history & average weekly earnings", plan="Growth+",
         summary="Weekly gross earnings per person (entered or CSV-imported). They feed holiday pay (52 weeks) and SSP/SMP (8 weeks).",
         how=["Zero-pay weeks are flagged: excluded from holiday pay, included (as £0) for SSP/SMP.",
              "Average weekly earnings = recorded weeks in the 8 weeks before the date."],
         code=[("src/app/api/team-members/[id]/earnings-history/route.ts", "Earnings API"),
               ("src/lib/earningsHistory.ts", "CSV parsing"),
               ("src/components/settings/earnings-coverage-panel.tsx", "Coverage of earnings data"),
               ("src/lib/smpCalculator.ts", "getAweForUser()")],
         refs=["holiday_pay", "ssp_pay", "rates"], related=["holidaypay", "ssp"]),
    dict(id="holidaypay", ch="pay", title="Holiday pay (52-week average)", plan="Growth+",
         summary="A day's holiday pay is the average weekly pay over the last 52 paid weeks (looking back up to 104) divided by the days they work.",
         how=["Daily rate = average week ÷ working days (£390 ÷ 3 = £130). Fixed 4 Oct 2026; it divided by 5 before.",
              "Irregular-hours staff use an hourly rate (pay ÷ hours).",
              "The rate is captured on each annual leave booking for payroll."],
         code=[("src/lib/holidayPay.ts", "calculateHolidayPayRate()"),
               ("src/lib/payroll-export.ts", "Rate fields in the export")],
         refs=["holiday_pay", "wtr16", "irregular"], related=["earnings", "payroll"]),
    dict(id="payroll", ch="pay", title="Payroll export", plan="All plans",
         summary="Approved leave in a date range with holiday pay rates and estimated pay, plus a separate “Cover shifts worked” export — CSV or Excel.",
         how=["Rows show whether the rate was captured at booking or recalculated.",
              "SMP and neonatal blocks are flattened into columns for payroll software."],
         code=[("src/app/api/reports/payroll/route.ts", "Payroll export"),
               ("src/lib/export-formats.ts", "CSV / Excel"),
               ("src/app/(dashboard)/reports/page.tsx", "Reports page (Payroll tab)")],
         refs=["holiday_pay"], related=["coverpay", "holidaypay"]),
    dict(id="reports", ch="pay", title="Compliance & operations reports", plan="Scale+ (some Growth+)",
         summary="One Reports page: operations, analytics, Bradford, absence trends, cover by location, right to work, weekly hours, holiday usage, SSP liability, parental tracker, payroll and year-end.",
         how=["“Export compliance pack” bundles the key tables.",
              "Monthly compliance email for Scale+ teams; weekly digest for everyone."],
         code=[("src/app/(dashboard)/reports/page.tsx", "Reports page"),
               ("src/app/api/reports/uk-compliance/route.ts", "UK compliance data"),
               ("src/app/api/reports/leave-operations/route.ts", "Operations"),
               ("src/lib/monthly-compliance-snapshot.ts", "Monthly email content"),
               ("src/app/api/cron/weekly-digest/route.ts", "Weekly digest")],
         refs=["ssp_employer", "rtw", "acas_absence"], docs=["vercel_cron"], related=["ssp", "bradford", "rtw"]),

    # ── Compliance & data ──
    dict(id="rtw", ch="data", title="Right to work", plan="Growth+",
         summary="Track whether each UK employee's right-to-work check is done. The dashboard and reports flag people without a verified check.",
         how=["Stored per person (verified / not / unknown); zero-hours workers are flagged separately."],
         code=[("src/components/team/member-form.tsx", "Right-to-work field"),
               ("src/app/(dashboard)/dashboard/page.tsx", "Dashboard warning"),
               ("src/lib/uk-workforce.ts", "UK workforce helpers")],
         refs=["rtw"], related=["reports"]),
    dict(id="audit", ch="data", title="Audit log & activity", plan="Viewer & exports: Pro",
         summary="Every important action — approvals, overrides, sickness logged, fit notes, cover requests, settings — is recorded with who, what and when.",
         how=["Pro teams also log sensitive reads (who viewed a sickness note or profile).",
              "Actions are a fixed list so filters stay consistent."],
         code=[("src/lib/audit.ts", "recordAudit(), AUDIT_ACTIONS"),
               ("src/app/(dashboard)/audit/page.tsx", "Audit page"),
               ("src/components/team/activity-log.tsx", "Per-person activity")],
         refs=["ico_employment"], related=["roles"]),
    dict(id="gdpr", ch="data", title="Subject access, retention & deletion", plan="All plans",
         summary="Export everything held on a person (UK GDPR Article 15), anonymise old records after a retention period, and delete a whole account with a 30-day grace period.",
         how=["SAR export is machine-readable JSON with secrets redacted.",
              "Retention anonymises records older than 6 years (configurable); sickness notes are always wiped.",
              "Account deletion is scheduled 30 days out and processed nightly."],
         code=[("src/lib/sar-export.ts", "SAR export"),
               ("src/app/api/admin/data-retention/route.ts", "Retention / anonymisation"),
               ("src/lib/deletionScheduler.ts", "Deletion scheduling"),
               ("src/app/api/cron/process-deletions/route.ts", "Nightly deletion job")],
         refs=["ico_sar", "ico_storage", "ico_employment"], related=["audit"]),
    dict(id="cookies", ch="data", title="Cookie consent & email preferences", plan="All plans",
         summary="Only essential cookies until a visitor accepts analytics. Digest emails have one-click unsubscribe.",
         how=["The banner reserves space so it never hides the bottom of a page.",
              "Unsubscribe links are signed tokens; List-Unsubscribe headers support Gmail/Outlook one-click."],
         code=[("src/components/cookie-banner.tsx", "Cookie banner"),
               ("src/lib/consent.ts", "Consent helpers"),
               ("src/lib/email-unsubscribe.ts", "Signed unsubscribe tokens")],
         refs=["ico_cookies"], docs=["rfc8058"], related=["analytics"]),
    dict(id="security", ch="data", title="Security controls", plan="All plans",
         summary="Rate limiting on sign-in and password routes, strict security headers, error tracking, and functions pinned to London.",
         how=["Upstash Redis rate limits (fail closed in production if not configured).",
              "Content Security Policy, HSTS, no framing; Sentry host read from the DSN.",
              "Vercel functions run in lhr1 (London), next to the database."],
         code=[("src/lib/rate-limit.ts", "Rate limiting"),
               ("next.config.ts", "Security headers, CSP"),
               ("vercel.json", "Region and cron schedules"),
               ("sentry.client.config.ts", "Error tracking")],
         refs=["ico_employment"], docs=["vercel_regions", "vercel_cron", "upstash", "sentry", "csp"], related=[]),

    # ── Integrations ──
    dict(id="billing", ch="integrations", title="Plans, billing & VAT", plan="—",
         summary="Five plans (Free, Starter, Growth, Scale, Pro). Stripe handles subscriptions, payment methods, trials and VAT.",
         how=["Stripe webhooks keep the plan in sync (paused, cancelled, payment failed → locked).",
              "Stripe Tax adds VAT on top; customers can add VAT numbers.",
              "Feature access is checked by plan everywhere (TRIAL = full access)."],
         code=[("src/lib/planFeatures.ts", "Features per plan"),
               ("src/config/pricing.ts", "Prices and plan copy"),
               ("src/lib/stripe-webhook-handlers.ts", "Webhook handling"),
               ("src/app/api/webhooks/stripe/route.ts", "Webhook endpoint"),
               ("src/components/billing/tax-section.tsx", "VAT numbers")],
         refs=[], docs=["stripe_billing", "stripe_tax", "stripe_webhooks"], related=["signup"]),
    dict(id="slack", ch="integrations", title="Slack & Jira", plan="All plans",
         summary="Slack: new requests posted with approve/reject buttons, DMs on decisions, and a /requestleave command. Jira: warns when someone with open tickets books leave and helps reassign them.",
         how=["Slack and web share the same create/review logic, so rules never diverge."],
         code=[("src/lib/slack-notifications.ts", "Slack messages"),
               ("src/app/api/slack/commands/route.ts", "/requestleave"),
               ("src/app/api/slack/interactions/route.ts", "Approve/reject buttons"),
               ("src/lib/jira.ts", "Jira integration"),
               ("src/components/leave/coverage-warning.tsx", "Jira coverage warning")],
         refs=[], docs=["slack_api", "jira_api"], related=["requests"]),
    dict(id="analytics", ch="integrations", title="Email & product analytics", plan="All plans",
         summary="Emails go through Resend (invites, approvals, cover requests, fit-note alerts). Product analytics (PostHog) only run with consent.",
         how=["Names in emails are HTML-escaped.",
              "PostHog is proxied through /ingest and gated on cookie consent."],
         code=[("src/lib/email.ts", "sendEmail()"),
               ("src/lib/email-templates.ts", "All email templates"),
               ("src/lib/analytics/server.ts", "Server analytics"),
               ("src/components/analytics/posthog-provider.tsx", "Client analytics")],
         refs=["ico_cookies"], docs=["resend", "posthog"], related=["cookies"]),

    # ── Growth ──
    dict(id="landing", ch="growth", title="Website, pricing, guides & tools", plan="Public",
         summary="The marketing site tells the 7:10am sick-call story, explains pricing, and publishes SEO guides and free calculators.",
         how=["Guides are markdown in /marketing; only files with a title and description are published (internal notes are excluded from the sitemap).",
              "Free tools: SSP calculator and irregular-hours holiday calculator.",
              "Logged-out 404s point to the homepage and guides."],
         code=[("src/components/landing/landing-page.tsx", "Homepage"),
               ("src/app/pricing/page.tsx", "Pricing page"),
               ("src/lib/guides.ts", "Guides loader"),
               ("src/app/sitemap.ts", "Sitemap"),
               ("src/app/tools/ssp-calculator/calculator.tsx", "SSP calculator")],
         refs=["ssp_amount", "irregular"], related=["signupalerts"]),
    dict(id="signupalerts", ch="growth", title="Signup alerts & founder outreach", plan="Internal",
         summary="You get an email when a team signs up and again when it finishes onboarding. The first 100 verified admins also get a personal email from you.",
         how=["SIGNUP_ALERT_TO sets recipients (default hello@coverboard.io; “off” disables; quiet on preview deploys).",
              "Founder outreach is capped (FOUNDER_OUTREACH_CAP) and sent once per team."],
         code=[("src/lib/signup-alerts.ts", "Signup alerts"),
               ("src/lib/founder-outreach.ts", "Founder email")],
         refs=[], docs=["resend"], related=["signup"]),
]

LIMITATIONS = [
    ("Calculations fixed on 4 Oct 2026", "Holiday pay, SSP days and earnings, family leave units, starter proration, carry-over units and fit-note evidence were corrected after tester feedback. Records created on production before the fix keep their old SSP figures until recalculated."),
    ("Unpaid parental leave follows the default scheme", "The statutory fallback rules (whole weeks, 4 weeks a year per child, the child's year) are applied. If you have a workforce or collective agreement, its rules take precedence and aren't enforced. Whole weeks aren't checked for part-timers with no working pattern, as the app can't tell which days they work."),
    ("Working days without a pattern", "Without a working pattern only the number of days is known, so Monday–Friday is assumed when counting which days were missed."),
    ("Average earnings with gaps", "Weeks with no earnings record are treated as missing, not £0. Record zero-pay weeks explicitly so averages are right."),
    ("Cover needs fixed weekly patterns", "Shift cover assumes the same pattern each week. Teams whose rota changes weekly will see inaccurate cover until a rota feature exists."),
    ("Weekly hours aren't automatic", "Irregular-hours accrual uses hours admins log; accepted cover is shown beside them but not added."),
    ("Not legal advice", "Coverboard implements published GOV.UK rules, but figures should be checked by your payroll provider before payment."),
]

DIAGRAM_NOTES = {
    "architecture": "Everything a request touches: the browser talks to the Next.js app on Vercel (London), which reads and writes Postgres through Prisma and calls out to third-party services. Scheduled jobs run on Vercel Cron.",
    "codemap": "Where things live. Pages and API routes are under src/app; reusable UI under src/components; business rules (the important part) under src/lib.",
    "datamodel": "The main tables and how they relate. An Organization has users, leave types, locations and cover offers; a user has leave requests, earnings, weekly hours and a working pattern.",
    "requestflow": "What happens when leave is booked: validation and statutory checks in createLeaveRequest(), then approval in reviewLeaveRequest(), each step recalculating derived numbers and recording an audit entry.",
    "coverflow": "The core story: a sick call becomes a recorded absence, the cover engine finds the gap and candidates, the manager asks, staff accept, and the shift is covered everywhere it matters.",
    "workingweek": "The single source of truth added on 4 Oct 2026: one answer to “which days does this person work?” feeds every pay and entitlement calculation.",
    "crons": "Background jobs scheduled in vercel.json.",
}


# ════════════════════════════════════════════════════════════════════════
# Updates, 7 Oct 2026: everything built since the 4 Oct edition.
# ════════════════════════════════════════════════════════════════════════
R.update({
    "wtr14": ("legislation.gov.uk – WTR reg. 14 (pay in lieu on leaving)", "https://www.legislation.gov.uk/uksi/1998/1833/regulation/14"),
    "wtr4": ("legislation.gov.uk – WTR reg. 4 (48-hour average)", "https://www.legislation.gov.uk/uksi/1998/1833/regulation/4"),
    "upl_sch2": ("legislation.gov.uk – Maternity and Parental Leave etc. Regs 1999, Sch. 2 (the 4-week year per child)", "https://www.legislation.gov.uk/uksi/1999/3312/schedule/2"),
    "sap_reg40": ("legislation.gov.uk – SPP and SAP (General) Regs 2002, reg. 40 (adoption earnings period)", "https://www.legislation.gov.uk/uksi/2002/2822/regulation/40"),
    "adoption_employer": ("GOV.UK – Employers: adoption pay and leave", "https://www.gov.uk/employers-adoption-pay-leave"),
    "adoption_elig": ("GOV.UK – Employers: adoption pay eligibility (matching week)", "https://www.gov.uk/employers-adoption-pay-leave/eligibility"),
    "spl_guide": ("GOV.UK – Shared Parental Leave and Pay: employer guide", "https://www.gov.uk/shared-parental-leave-and-pay-employer-guide"),
    "spl_tech": ("GOV.UK – Shared parental leave and pay: employers' technical guide", "https://www.gov.uk/government/publications/shared-parental-leave-and-pay-employers-technical-guide/shared-parental-leave-and-pay-employers-technical-guide-to-shared-parental-leave-and-pay-html-version"),
    "neonatal_elig": ("GOV.UK – Employers: neonatal care pay eligibility (relevant week)", "https://www.gov.uk/employers-neonatal-care-pay-leave/eligibility"),
    "hmrc_continuous": ("HMRC manual – Continuous employment (statutory payments)", "https://www.gov.uk/hmrc-internal-manuals/statutory-payments-manual/spm250100"),
    "maternity_tech": ("GOV.UK – Maternity benefits: technical guidance (26 weeks into the qualifying week)", "https://www.gov.uk/government/publications/maternity-benefits-technical-guidance/maternity-benefits-technical-guidance"),
})

_UPDATES = {
    "team": dict(
        summary="The Team page lists everyone with their location, contract and work country. Each profile holds contract details, start date, right-to-work checks, earnings history, working pattern, 48-hour opt-out and children (for unpaid parental leave).",
        how=["Work country (not “location”) decides which statutory rules apply.",
             "Days per week on the profile come from their working pattern, and the stored figure is corrected if it drifts.",
             "The start date drives starter proration and the 26-week service tests for family pay.",
             "People who leave are marked as left, not deleted (see Leavers): holiday records must be kept for 6 years."],
        code=[("src/app/(dashboard)/team/page.tsx", "Team list"),
              ("src/app/(dashboard)/team/[id]/page.tsx", "Profile, leaving dialog"),
              ("src/components/team/member-card.tsx", "Team card (Left / Leaving badges)"),
              ("src/app/api/team-members/[id]/route.ts", "Profile API; marking as left"),
              ("src/components/team/children.tsx", "Children for unpaid parental leave")],
        related=["leavers", "workingweek", "rtw", "earnings"]),
    "requests": dict(
        summary="Staff request time off; managers approve or reject, or record leave for someone (approved straight away, and they're emailed). Requests check notice, balances, overlap and minimum cover.",
        how=["Notice is counted in whole calendar days; sickness and manager-recorded leave need none.",
             "Pending requests can be withdrawn; approved leave only before it starts.",
             "Admins and managers can cancel someone's approved upcoming leave, after an “Are you sure?” that says the person will be emailed.",
             "Approving below minimum cover asks for an explicit override, recorded in the audit log.",
             "Family leave asks for the dates its pay depends on: due date, matching date, days in neonatal care, and whether shared parental pay is claimed."],
        code=[("src/lib/leave-requests/create.ts", "createLeaveRequest(): every check and pay calculation at booking"),
              ("src/lib/leave-requests/review.ts", "Approve/reject"),
              ("src/app/api/leave-requests/[id]/route.ts", "Cancel, and dates added after booking"),
              ("src/components/leave/request-form.tsx", "Booking form"),
              ("src/components/leave/request-card.tsx", "Request cards with pay panels"),
              ("src/app/(dashboard)/requests/page.tsx", "Requests page, cancel confirmation")],
        related=["balances", "covercheck", "audit", "maternity"]),
    "balances": dict(
        summary="Each person's allowance, days used, pending and remaining, per leave type and leave year. UK entitlement is 5.6 weeks of their working week, capped at 28 days.",
        how=["Entitlement = 5.6 × working days per week, rounded up, capped at 28: 28 for a 5-day week, 17 for 3 days.",
             "Mid-year starters get their share of the leave year from their start date, rounded up (never down).",
             "Days taken only count days they'd actually have worked.",
             "Carry-over is used first, soonest-expiring first; when it expires only the unused part lapses.",
             "Everything counts within the team's leave year (see Leave year)."],
        code=[("src/lib/leave-balances.ts", "getUserLeaveBalances()"),
              ("src/lib/uk-compliance.ts", "UK entitlement rules"),
              ("src/lib/working-week.ts", "Working week, starter proration"),
              ("src/lib/carry-over.ts", "carryOverInEffect()")],
        related=["leaveyear", "workingweek", "irregular", "carryover"]),
    "carryover": dict(
        summary="At the leave year end, the rollover carries leave forward for four reasons, each with its own expiry, and shows a per-person preview before it runs.",
        how=["After sickness: the untaken part of the 4 weeks (all untaken hours for irregular-hours staff), no more than the days off, for 18 months (reg. 13(15)).",
             "After family leave: all statutory leave they couldn't take, including the extra 1.6 weeks (up to 28 days), to the end of next year (reg. 13(14), 13A(7A)).",
             "When the employer didn't give the chance to take it, or warn it would be lost: the untaken 4 weeks, to the end of next year (reg. 13(16)–(18)). A per-person tick.",
             "Company carry-over: from what's left, up to the team's cap, expiring on the date set in Settings (with the actual date and warnings shown).",
             "Longer-lasting reasons are applied first, so nothing counts twice; re-running replaces that person's carry-over."],
        code=[("src/lib/carry-over.ts", "planYearEndCarryOver(): the four reasons"),
              ("src/app/api/carry-over/process/route.ts", "Preview and run"),
              ("src/app/(dashboard)/reports/page.tsx", "Year-end rollover screen")],
        refs=["wtr13", "acas_holiday_sick", "holiday"],
        related=["balances", "leaveyear"]),
    "statutorytypes": dict(
        how=["Paternity 2 weeks · Bereavement 2 · Unpaid parental 4 a year per child (18 per child) · Carer's 1 · Maternity 52 · Adoption 52 · Shared parental 50 · Neonatal 12.",
             "LeaveType.allowanceUnit = WEEKS; balances multiply by their working days (2 weeks = 10 days on 5 days, 6 on 3).",
             "The parental tracker, compliance pack and return alerts read one shared list of these types, so none is missed."]),
    "maternity": dict(
        title="Maternity & adoption: SMP and SAP",
        summary="52 weeks' leave (a day-one right). Statutory Maternity or Adoption Pay: 6 weeks at 90% of average weekly earnings, then 33 weeks at the lower of the flat rate or 90%.",
        how=["Maternity: earnings from the 8 weeks up to the qualifying week (15 weeks before the due week); 26 weeks' service by then.",
             "Adoption: the same, from the matching week (the week they were told of the match).",
             "26 weeks counts Sunday–Saturday weeks and any part of a week, so the latest start is the Saturday 25 weeks before (corrected 7 Oct; it was a week too strict).",
             "Recalculated whenever earnings change and when the request is viewed; the card shows the week, the rates, the last day of each phase and how many of the 8 weeks had pay.",
             "The due or matching date can be added on the card after booking.",
             "Payroll pays the days of each pay period at the weekly rate ÷ 7, split across the 90% and flat-rate weeks."],
        code=[("src/lib/smp-dates.ts", "Qualifying/matching week, service test, pay per period"),
              ("src/lib/smp-request.ts", "computeSmpFields(), recalculation"),
              ("src/lib/smpCalculator.ts", "Rates and average earnings"),
              ("src/components/leave/smp-summary.tsx", "Pay panels on request cards")],
        refs=["maternity_employer", "adoption_employer", "adoption_elig", "sap_reg40", "maternity_tech", "hmrc_continuous", "rates"],
        related=["kit", "earnings", "payroll"]),
    "paternity": dict(
        title="Paternity leave & SPP",
        summary="1 or 2 weeks (may be split), within 52 weeks of the birth or placement. Statutory Paternity Pay: the lower of the flat rate or 90% of average weekly earnings.",
        how=["Booking asks whether it's for a birth or an adoption, then the due date or matching date.",
             "Earnings from the 8 weeks up to the qualifying week (or matching week), with 26 weeks' service by then; the card names the week.",
             "Without a date, it uses the leave start and says so; the date can be added on the card."],
        code=[("src/lib/smp-request.ts", "computeSpp() (shared with ShPP and neonatal pay)"),
              ("src/lib/smp-dates.ts", "parentPayDates(): which date counts"),
              ("src/lib/leave-requests/create.ts", "52-week window")],
        refs=["paternity_employer", "paternity"],
        related=["spl", "maternity"]),
    "neonatal": dict(
        summary="One week of leave and pay for every 7 full days in neonatal care, up to 12, taken within 68 weeks of the birth. Pay: the lower of the flat rate or 90% of earnings.",
        how=["Booking records the first and last full days in care (employers must keep them); older bookings can add them on the card.",
             "Pay week: the qualifying or matching week if they'd get SMP, SPP or SAP, otherwise the week before the baby went into care. The card names it.",
             "Bookings beyond the weeks the time in care gives, or past 68 weeks, are refused (or flagged on older bookings).",
             "Shown on the parental tracker and compliance pack; payroll pays calendar days at the weekly rate ÷ 7."],
        code=[("src/lib/neonatalPay.ts", "Weeks from time in care, booking checks"),
              ("src/lib/smp-request.ts", "computeSncp()")],
        refs=["neonatal_employer", "neonatal_elig", "neonatal"],
        related=["maternity", "payroll"]),
    "otherfamily": dict(
        summary="Parental bereavement leave (2 weeks), unpaid parental leave (18 weeks per child, at most 4 a year per child) and carer's leave (1 week a year).",
        how=["Children are recorded on the profile, with weeks taken with previous employers, a placement date if adopted, and whether they get a disability benefit.",
             "The 4-week limit runs in each child's own year: 12 months from when the employee became entitled, renewing each anniversary. That's the birth or placement, or their start date if later (a day-one right since 6 April 2026; before then, a year's service).",
             "Weeks are their working week (4 weeks = 12 days for a 3-day worker); leave must end before the child's 18th birthday.",
             "Leave is booked in whole weeks unless the child gets Disability Living Allowance, Personal Independence Payment or Armed Forces Independence Payment, when single days are allowed."],
        code=[("src/lib/unpaid-parental.ts", "Per-child limits and the child's year"),
              ("src/lib/children-server.ts", "Children and usage"),
              ("src/lib/leave-requests/create.ts", "Booking checks")],
        refs=["upl", "upl_sch2", "bereavement", "carers"],
        related=["statutorytypes", "team"]),
    "payroll": dict(
        summary="Approved leave in a pay period with holiday pay and every statutory payment for the days in that period, plus leavers' final holiday pay and a “Cover shifts worked” export, as CSV or Excel.",
        how=["Statutory pay is worked out for the pay period, not today: SSP, SMP or SAP (with a column saying which), SPP, ShPP and neonatal pay, each at the weekly rate ÷ 7 for calendar days.",
             "The screen shows working days, calendar days, rate and pay per row, and a statutory pay total split by type.",
             "Leavers whose last day is in the period get their own table, Excel sheet and CSV: built up, taken and holiday to pay.",
             "Money on screen has thousands separators; exports keep plain numbers."],
        code=[("src/app/api/reports/payroll/route.ts", "Builds the report and exports"),
              ("src/lib/payroll-columns.ts", "Columns, defined once for screen and export"),
              ("src/lib/export-formats.ts", "CSV and Excel"),
              ("src/app/(dashboard)/reports/page.tsx", "Payroll screen")],
        refs=["holiday_pay", "wtr14", "ssp_pay"],
        related=["coverpay", "holidaypay", "leavers"]),
    "reports": dict(
        summary="One Reports page: operations, analytics, Bradford, absence trends, cover by location, right to work, working time, holiday usage, SSP liability, parental tracker, payroll and year-end.",
        how=["Holiday usage counts the team's leave year and includes bookings across its start or end.",
             "The parental tracker shows SMP/SAP rates (even before pay starts), ShPP, neonatal pay and weeks, KIT/SPLIT days.",
             "“Export compliance pack” bundles the key tables; columns are defined once for screen and export.",
             "Monthly compliance email for Scale+ teams; weekly digest for everyone."],
        code=[("src/app/(dashboard)/reports/page.tsx", "Reports page"),
              ("src/app/api/reports/uk-compliance/route.ts", "UK compliance data"),
              ("src/lib/uk-compliance-columns.ts", "Columns and the parental leave list"),
              ("src/app/api/cron/monthly-compliance-report/route.ts", "Monthly email")],
        related=["ssp", "bradford", "rtw", "workingtime"]),
    "rtw": dict(
        summary="Record each right-to-work check with its date, method, document and any expiry. Expired permission and rechecks due within 60 days are flagged everywhere, including the Monday email.",
        how=["Checks are kept as a history; the latest sets the person's status.",
             "Time-limited permission must be checked again before it ends.",
             "Checks are removed 2 years after someone leaves."],
        code=[("src/components/team/right-to-work-card.tsx", "Profile card"),
              ("src/lib/right-to-work.ts", "Status rules"),
              ("src/app/api/team-members/[id]/right-to-work/route.ts", "Recording checks")],
        related=["reports", "leavers"]),
    "gdpr": dict(
        summary="Export everything held on a person (UK GDPR Article 15), keep holiday records for 6 years, remove former staff after the legal periods, and delete a whole account with a 30-day grace period.",
        how=["SAR export is machine-readable JSON with secrets redacted.",
             "Former staff are removed 6 years after leaving (right-to-work checks after 2), by the nightly job.",
             "Account deletion offers a 6-year records download first, is scheduled 30 days out and processed nightly."],
        code=[("src/lib/sar-export.ts", "Subject access export"),
              ("src/lib/former-staff-retention.ts", "Removal after the legal periods"),
              ("src/lib/deletionScheduler.ts", "Account deletion"),
              ("src/app/api/cron/process-deletions/route.ts", "Nightly job")]),
}

_NEW = [
    ("team", dict(id="leavers", ch="start", title="Leavers & holiday owed", plan="All plans",
         summary="Admins set someone's last day: in the past if recorded late, or ahead while they work their notice. Their profile shows the holiday they're owed in their final pay.",
         how=["The dialog previews what the date cancels or cuts short, and warns when a past date makes them former staff straight away.",
              "A future date keeps them on the team until then; the nightly job marks them as left the day after.",
              "Leave after the last day is cancelled, leave running past it is cut short (SSP recalculated), and cover is withdrawn.",
              "Holiday owed: (entitlement × share of the year worked) − taken, plus carry-over still owed, valued at the 52-week average (reg. 14). Over-taken leave can only be recovered if agreed in writing.",
              "Leavers appear in the payroll export for the period of their last day."],
         code=[("src/lib/leavers.ts", "recordLeaving(), previewLeaving(), nightly step"),
               ("src/lib/holiday-on-leaving.ts", "(A × B) − C"),
               ("src/lib/holiday-on-leaving-server.ts", "Holiday owed for a leaver"),
               ("src/components/team/holiday-on-leaving-card.tsx", "Profile card")],
         refs=["wtr14", "leaving"], docs=[], related=["team", "payroll", "gdpr"])),
    ("balances", dict(id="leaveyear", ch="leave", title="Leave year", plan="All plans",
         summary="Each team sets when its holiday year starts (1 January by default; 1 April is common). Allowances, starters, bank holidays, carry-over, holiday usage and the rollover all count from it.",
         how=["A leave year is named by the year it starts in: an April year shows as 2026/27.",
              "Changing it asks for confirmation, shows the old and new years and what moves, and saves month and day together.",
              "Carry-over expiry shows the real date, with warnings when carried days would last the whole next year or less than a month.",
              "Unpaid parental leave has its own per-child year, not this one."],
         code=[("src/lib/leave-year.ts", "Leave year rules"),
               ("src/lib/leave-year-server.ts", "The team's setting"),
               ("src/app/(dashboard)/settings/page.tsx", "Leave year card")],
         refs=["holiday_entitlement", "wtr13"], docs=[], related=["balances", "carryover"])),
    ("paternity", dict(id="spl", ch="family", title="Shared parental leave & ShPP", plan="Growth+",
         summary="Up to 50 weeks shared, with Shared Parental Pay for up to 37: the lower of the flat rate or 90% of earnings, every week.",
         how=["Each booking says whether their notice claims pay for those weeks; unpaid blocks show as £0 in payroll.",
              "The pool is 39 weeks less the mother's or adopter's own SMP/SAP weeks (at least 2) when the app holds them, otherwise 37.",
              "Claims over the pool are refused; the card shows the weeks left and the week the pay comes from.",
              "The partner's eligibility is their declaration; employers don't have to check it."],
         code=[("src/lib/smp-dates.ts", "shppPoolWeeks(), shppClaimError()"),
               ("src/lib/smp-request.ts", "computeShpp(), shppPoolForChild()")],
         refs=["spl_guide", "spl_tech", "spl"], docs=[], related=["maternity", "paternity", "kit"])),
    ("reports", dict(id="workingtime", ch="pay", title="Working time (48 hours, rest)", plan="All plans (UK staff)",
         summary="A working-time report: average weekly hours over 17 weeks against the 48-hour limit, weeks over 48, and rest under 11 hours between shifts, with this week and next as rostered.",
         how=["Hours come from logged hours, else hours on pay records, else the working pattern and accepted cover, minus leave: an estimate, not timesheets.",
              "New starters are averaged since they started (or their first recorded work).",
              "48-hour opt-outs are recorded on profiles; over the average without one is flagged."],
         code=[("src/lib/working-time.ts", "summariseWorkingTime()"),
               ("src/components/reports/working-time-section.tsx", "Report section")],
         refs=["wtr4", "maxhours", "wtr10", "rest"], docs=[], related=["reports", "patterns"])),
]

for _f in FEATURES:
    _f.update(_UPDATES.get(_f["id"], {}))
for _after, _feature in _NEW:
    _i = next(i for i, f in enumerate(FEATURES) if f["id"] == _after)
    FEATURES.insert(_i + 1, _feature)

LIMITATIONS = [
    ("Calculations corrected 4–7 Oct 2026", "Holiday pay, SSP, SMP and other family pay, starter proration, carry-over and the 26-week service test were corrected after tester feedback. Run npm run recalculate:ssp after deploying to refresh stored SSP and SMP."),
    ("Shared parental pay pool", "The app only sees this employee's claims and their own maternity or adoption pay; the other parent's share comes off the same pool."),
    ("Overseas adoption and surrogacy", "Their pay dates differ (arrival in the UK, or 15 weeks before the due date) and should be worked out by hand."),
    ("Unpaid parental leave year", "Uses the default scheme's per-child year; a collective or workforce agreement that sets another year isn't supported."),
    ("Working days without a pattern", "Without a working pattern only the number of days is known, so Monday–Friday is assumed when counting which days were missed."),
    ("Average earnings with gaps", "Weeks with no earnings record are treated as missing, not £0, and the card says so. Record zero-pay weeks explicitly so averages are right."),
    ("Cover needs fixed weekly patterns", "Shift cover assumes the same pattern each week. Teams whose rota changes weekly will see inaccurate cover until a rota feature exists."),
    ("Holiday on leaving", "Covers the allowance the app knows; contract terms such as rounding up to half days are for the employer."),
    ("Not legal advice", "Coverboard implements published GOV.UK and legislation.gov.uk rules, but figures should be checked by your payroll provider before payment."),
]
